# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install production dependencies deterministically
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

# Bundle app source only
COPY src ./src

# Ensure executable bit (optional for shebang)
RUN chmod +x src/server.js || true

# Start the server
CMD ["node", "src/server.js"]
