# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Bundle app source
COPY . .

# Expose port if needed (not used for stdio)
# RUN chmod +x src/server.js

# Start the server
CMD ["node", "src/server.js"]
